name: with-versions

on:
  workflow_dispatch:
    inputs:
      dcl-sdk-package:
        type: string
        description: "@dcl/sdk package"
        default: "@dcl/sdk@next"
      dcl-cli:
        type: string
        description: "decentraland package"
        default: "decentraland@next"

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install fixed sdk
        run: ./install-fixed-sdk.sh
        env:
          SDK_VERSION: ${{github.event.inputs.dcl-sdk-package}}
      - name: install decentraland
        run: npm i -g ${{github.event.inputs.dcl-cli}}
      - name: install dependencies
        run: npm i
      - name: build
        run: dcl build
